name: commutemate
description: "Fixed version of the Why Jam Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'  # More precise version constraint

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.12.3
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  http: ^1.4.0
  flutter_typeahead: ^5.2.0  # Not used in current code but good to have
  flutter_polyline_points: ^2.1.0
  geocoding: ^2.1.0
  google_places_flutter: ^2.1.0
  cached_network_image: ^3.2.3
  url_launcher: ^6.1.7
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  flutter_tts: ^3.6.3 
  vector_math: ^2.1.4 
  wakelock_plus: ^1.3.2
  intl: ^0.18.1
  flutter_dotenv: ^5.1.0  # Recommended for API key management
  haptic_feedback: ^0.5.1+1  # Needed for your HapticFeedback usage

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/navigation_arrow.png
    - assets/minimal_map_style.json
    - .env  # For API key management if using flutter_dotenv